# Generated by Django 2.0.4 on 2018-04-25 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('revenue_from', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='From')),
                ('revenue_to', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='To')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
